In [2]:
from datetime import datetime
import pandas as pd
import json

from preprocessing import year

In [3]:
df = pd.read_csv('./irish-property-sales.csv', encoding="latin1")

column_names = [
    'date_of_sale',
    'address',
    'county',
    'eircode',
    'price',
    'not_full_market_price',
    'vat_exclusive',
    'property_description',
    'propterty_size_description'
]


def get_county_province_mapping(county: str):
    county = county.lower().strip()
    county_to_province = {
        "galway": "Connacht",
        "leitrim": "Connacht",
        "mayo": "Connacht",
        "roscommon": "Connacht",
        "sligo": "Connacht",
        "carlow": "Leinster",
        "dublin": "Leinster",
        "kildare": "Leinster",
        "kilkenny": "Leinster",
        "laois": "Leinster",
        "longford": "Leinster",
        "louth": "Leinster",
        "meath": "Leinster",
        "offaly": "Leinster",
        "westmeath": "Leinster",
        "wexford": "Leinster",
        "wicklow": "Leinster",
        "clare": "Munster",
        "cork": "Munster",
        "kerry": "Munster",
        "limerick": "Munster",
        "tipperary": "Munster",
        "waterford": "Munster",
        "antrim": "Ulster",
        "armagh": "Ulster",
        "cavan": "Ulster",
        "donegal": "Ulster",
        "down": "Ulster",
        "fermanagh": "Ulster",
        "londonderry": "Ulster",
        "monaghan": "Ulster",
        "tyrone": "Ulster",
    }

    return county_to_province[county]


def clean_price_column(price: str):
    cleaned = price[2:-1].replace(',', '')
    return float(cleaned)


def clean_property_description(desc: str):
    if desc == 'Second-Hand Dwelling house /Apartment':
        return 'second-hand'
    return 'new'


def map_property_size(property_size_desc: str):
    if property_size_desc in ["less than 38 sq metres", "n?os l? n? 38 m?adar cearnach"]:
        return "small"
    if property_size_desc in ["greater than or equal to 38 sq metres and less than 125 sq metres",
                              "níos mó ná nó cothrom le 38 méadar cearnach agus níos lú ná 125 méadar cearnach"]:
        return "medium"
    if property_size_desc in ["greater than 125 sq metres", "greater than or equal to 125 sq metres"]:
        return "large"

    return ""


def convert_to_iso_date(date: str):
    for fmt in ("%d/%m/%y", "%d/%m/%Y"):
        try:
            return datetime.strptime(date, fmt)
        except ValueError:
            continue
    raise ValueError(f'Unknown date format: {date}')


def map_address(full_address: str):
    return full_address.replace(' ', '_').strip().lower()


def map_county(county: str):
    return 'Laoighis' if county == 'Laois' else county


df.columns = column_names

df['date_of_sale'] = df['date_of_sale'].map(convert_to_iso_date)
df['year'] = df['date_of_sale'].map(lambda date: date.year)
df['address'] = df['address'].map(map_address)
df['price'] = df['price'].map(clean_price_column)
df['province'] = df['county'].map(get_county_province_mapping)
df['county'] = df['county'].map(map_county)
df['not_full_market_price'] = df['not_full_market_price'].map(lambda s: s.lower())
df['vat_exclusive'] = df['vat_exclusive'].map(lambda s: True if s == 'Yes' else False)
df['property_size'] = df['propterty_size_description'].map(map_property_size)
df['property_description'] = df['property_description'].map(clean_property_description)

/var/folders/nh/yh9mg2mx39ng5t5l9bd8r2400000gn/T/ipykernel_57853/4226063268.py:1: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('./irish-property-sales.csv', encoding="latin1")

In [4]:
df.head()

,date_of_sale,address,county,eircode,price,not_full_market_price,vat_exclusive,property_description,propterty_size_description,year,province,property_size
0,2010-01-01,"5_braemor_drive,_churchtown,_co.dublin",Dublin,NaN,343000.0,no,False,second-hand,NaN,2010,Leinster,
1,2010-01-03,"134_ashewood_walk,_summerhill_lane,_portlaoise",Laoighis,NaN,185000.0,no,True,new,greater than or equal to 38 sq metres and less...,2010,Leinster,medium
2,2010-01-04,"1_meadow_avenue,_dundrum,_dublin_14",Dublin,NaN,438500.0,no,False,second-hand,NaN,2010,Leinster,
3,2010-01-04,"1_the_haven,_mornington",Meath,NaN,400000.0,no,False,second-hand,NaN,2010,Leinster,
4,2010-01-04,"11_melville_heights,_kilkenny",Kilkenny,NaN,160000.0,no,False,second-hand,NaN,2010,Leinster,

In [5]:
mean_price_per_county_per_year = df.groupby(["county", "year"])["price"].mean().reset_index()
result = []

for county, sub in mean_price_per_county_per_year.groupby("county"):
    avg_list = [
        {
            "year": int(row["year"]),
            "average": float(row["price"]),
        }
        for _, row in sub.iterrows()
    ]

    result.append({
        "county": str(county),
        "averagePrice": avg_list,
    })

with open("meanPriceCounties.json", "w") as f:
    json.dump(result, f, indent=2)

In [6]:
grouped = (
    df.groupby(['year', 'property_description'])
    .size()
    .reset_index(name='count')
    .pivot(index='year', columns='property_description', values='count')
    .reset_index()
)
grouped.head()

property_description  year   new  second-hand
0                     2010  5315        15686
1                     2011  2956        15484
2                     2012  3179        22193
3                     2013  3896        26322
4                     2014  5424        38246

In [7]:
result = []
for _, row in grouped.iterrows():
    result.append({
        'year': int(row['year']),
        'new': int(row['new']),
        'secondHand': int(row['second-hand']),

    })

print(result)
with open("numberOfPropertyTypesPerYear.json", "w") as f:
    json.dump(result, f, indent=2)

[{'year': 2010, 'new': 5315, 'secondHand': 15686}, {'year': 2011, 'new': 2956, 'secondHand': 15484}, {'year': 2012, 'new': 3179, 'secondHand': 22193}, {'year': 2013, 'new': 3896, 'secondHand': 26322}, {'year': 2014, 'new': 5424, 'secondHand': 38246}, {'year': 2015, 'new': 6245, 'secondHand': 42918}, {'year': 2016, 'new': 6879, 'secondHand': 43055}, {'year': 2017, 'new': 9359, 'secondHand': 45659}, {'year': 2018, 'new': 11103, 'secondHand': 46347}, {'year': 2019, 'new': 11360, 'secondHand': 47697}, {'year': 2020, 'new': 9447, 'secondHand': 40101}, {'year': 2021, 'new': 9571, 'secondHand': 50012}, {'year': 2022, 'new': 11003, 'secondHand': 51723}, {'year': 2023, 'new': 12111, 'secondHand': 51211}, {'year': 2024, 'new': 12936, 'secondHand': 48519}, {'year': 2025, 'new': 9978, 'secondHand': 36811}]

In [30]:
df_year_price = df[['year', 'price']]
result = []
for year in df_year_price['year'].unique():
    bins = [0, 100000, 200000, 300000, 400000, 500000, 750000, 1000000, 2000000]
    labels = ['0-100k', '100-200k', '200-300k', '300-400k', '400-500k', '500-750k', '750k-1M', '1M+']
    price_bins = pd.cut(df_year_price[df_year_price['year'] == year]['price'], bins=bins, labels=labels, include_lowest=True)
    print(price_bins)

    result.append({
        'year': int(year),
        'bins': bins,
        'priceBins': price_bins.value_counts().sort_index().to_list()
    })

print(result)
with open("priceBinsPerYear.json", "w") as f:
    json.dump(result, f, indent=2)

0        300-400k
1        100-200k
2        400-500k
3        300-400k
4        100-200k
           ...
20996    300-400k
20997    200-300k
20998      0-100k
20999      0-100k
21000    100-200k
Name: price, Length: 21001, dtype: category
Categories (8, object): ['0-100k' < '100-200k' < '200-300k' < '300-400k' < '400-500k' < '500-750k' < '750k-1M' < '1M+']
21001    100-200k
21002    200-300k
21003    100-200k
21004    300-400k
21005    100-200k
           ...
39436      0-100k
39437      0-100k
39438      0-100k
39439    200-300k
39440      0-100k
Name: price, Length: 18440, dtype: category
Categories (8, object): ['0-100k' < '100-200k' < '200-300k' < '300-400k' < '400-500k' < '500-750k' < '750k-1M' < '1M+']
39441    100-200k
39442    100-200k
39443    100-200k
39444      0-100k
39445    100-200k
           ...
64808    100-200k
64809    200-300k
64810      0-100k
64811      0-100k
64812    100-200k
Name: price, Length: 25372, dtype: category
Categories (8, object): ['0-100k' < '100-200k' < '200-300k' < '300-400k' < '400-500k' < '500-750k' < '750k-1M' < '1M+']
64813      0-100k
64814    100-200k
64815    500-750k
64816      0-100k
64817    100-200k
           ...
95026    200-300k
95027      0-100k
95028    100-200k
95029    100-200k
95030    100-200k
Name: price, Length: 30218, dtype: category
Categories (8, object): ['0-100k' < '100-200k' < '200-300k' < '300-400k' < '400-500k' < '500-750k' < '750k-1M' < '1M+']
95031       0-100k
95032       0-100k
95033     100-200k
95034       0-100k
95035       0-100k
            ...
138696      0-100k
138697      0-100k
138698      0-100k
138699    300-400k
138700    200-300k
Name: price, Length: 43670, dtype: category
Categories (8, object): ['0-100k' < '100-200k' < '200-300k' < '300-400k' < '400-500k' < '500-750k' < '750k-1M' < '1M+']
138701      0-100k
138702    100-200k
138703    200-300k
138704      0-100k
138705     750k-1M
            ...
187859    100-200k
187860    300-400k
187861    200-300k
187862    300-400k
187863    100-200k
Name: price, Length: 49163, dtype: category
Categories (8, object): ['0-100k' < '100-200k' < '200-300k' < '300-400k' < '400-500k' < '500-750k' < '750k-1M' < '1M+']
187864    100-200k
187865      0-100k
187866    100-200k
187867    200-300k
187868    100-200k
            ...
237793      0-100k
237794    100-200k
237795    100-200k
237796    100-200k
237797      0-100k
Name: price, Length: 49934, dtype: category
Categories (8, object): ['0-100k' < '100-200k' < '200-300k' < '300-400k' < '400-500k' < '500-750k' < '750k-1M' < '1M+']
237798    200-300k
237799    200-300k
237800    500-750k
237801    500-750k
237802    500-750k
            ...
292811      0-100k
292812    300-400k
292813    100-200k
292814    200-300k
292815    200-300k
Name: price, Length: 55018, dtype: category
Categories (8, object): ['0-100k' < '100-200k' < '200-300k' < '300-400k' < '400-500k' < '500-750k' < '750k-1M' < '1M+']
292816    500-750k
292817    100-200k
292818    500-750k
292819    500-750k
292820    100-200k
            ...
350261    100-200k
350262         1M+
350263    200-300k
350264      0-100k
350265    100-200k
Name: price, Length: 57450, dtype: category
Categories (8, object): ['0-100k' < '100-200k' < '200-300k' < '300-400k' < '400-500k' < '500-750k' < '750k-1M' < '1M+']
350266      0-100k
350267      0-100k
350268      0-100k
350269      0-100k
350270    100-200k
            ...
409318      0-100k
409319    300-400k
409320     750k-1M
409321    300-400k
409322      0-100k
Name: price, Length: 59057, dtype: category
Categories (8, object): ['0-100k' < '100-200k' < '200-300k' < '300-400k' < '400-500k' < '500-750k' < '750k-1M' < '1M+']
409323    100-200k
409324    200-300k
409325    400-500k
409326    200-300k
409327    100-200k
            ...
458866    300-400k
458867    300-400k
458868         1M+
458869      0-100k
458870    400-500k
Name: price, Length: 49548, dtype: category
Categories (8, object): ['0-100k' < '100-200k' < '200-300k' < '300-400k' < '400-500k' < '500-750k' < '750k-1M' < '1M+']
458871    200-300k
458872    300-400k
458873    400-500k
458874    100-200k
458875    100-200k
            ...
518449     750k-1M
518450      0-100k
518451    200-300k
518452    100-200k
518453     750k-1M
Name: price, Length: 59583, dtype: category
Categories (8, object): ['0-100k' < '100-200k' < '200-300k' < '300-400k' < '400-500k' < '500-750k' < '750k-1M' < '1M+']
518454      0-100k
518455      0-100k
518456      0-100k
518457    100-200k
518458    100-200k
            ...
581175      0-100k
581176    200-300k
581177    200-300k
581178    300-400k
581179    100-200k
Name: price, Length: 62726, dtype: category
Categories (8, object): ['0-100k' < '100-200k' < '200-300k' < '300-400k' < '400-500k' < '500-750k' < '750k-1M' < '1M+']
581180    100-200k
581181    100-200k
581182    100-200k
581183    300-400k
581184      0-100k
            ...
644497    500-750k
644498    200-300k
644499    100-200k
644500    200-300k
644501    100-200k
Name: price, Length: 63322, dtype: category
Categories (8, object): ['0-100k' < '100-200k' < '200-300k' < '300-400k' < '400-500k' < '500-750k' < '750k-1M' < '1M+']
644502    200-300k
644503         1M+
644504    400-500k
644505    400-500k
644506    300-400k
            ...
705952         1M+
705953    300-400k
705954      0-100k
705955    200-300k
705956    100-200k
Name: price, Length: 61455, dtype: category
Categories (8, object): ['0-100k' < '100-200k' < '200-300k' < '300-400k' < '400-500k' < '500-750k' < '750k-1M' < '1M+']
705957    200-300k
705958    200-300k
705959    300-400k
705960    200-300k
705961    200-300k
            ...
752741    300-400k
752742    100-200k
752743    400-500k
752744    100-200k
752745    500-750k
Name: price, Length: 46789, dtype: category
Categories (8, object): ['0-100k' < '100-200k' < '200-300k' < '300-400k' < '400-500k' < '500-750k' < '750k-1M' < '1M+']
[{'year': 2010, 'bins': [0, 100000, 200000, 300000, 400000, 500000, 750000, 1000000, 2000000], 'priceBins': [2643, 7826, 6092, 2355, 941, 756, 202, 146]}, {'year': 2011, 'bins': [0, 100000, 200000, 300000, 400000, 500000, 750000, 1000000, 2000000], 'priceBins': [4215, 7149, 3931, 1549, 648, 610, 187, 121]}, {'year': 2012, 'bins': [0, 100000, 200000, 300000, 400000, 500000, 750000, 1000000, 2000000], 'priceBins': [7811, 9767, 4271, 1715, 725, 684, 206, 137]}, {'year': 2013, 'bins': [0, 100000, 200000, 300000, 400000, 500000, 750000, 1000000, 2000000], 'priceBins': [10834, 10127, 4521, 2021, 1056, 1025, 332, 221]}, {'year': 2014, 'bins': [0, 100000, 200000, 300000, 400000, 500000, 750000, 1000000, 2000000], 'priceBins': [14251, 14443, 7411, 3353, 1596, 1625, 495, 374]}, {'year': 2015, 'bins': [0, 100000, 200000, 300000, 400000, 500000, 750000, 1000000, 2000000], 'priceBins': [14084, 15878, 9944, 4204, 2025, 1941, 560, 426]}, {'year': 2016, 'bins': [0, 100000, 200000, 300000, 400000, 500000, 750000, 1000000, 2000000], 'priceBins': [12176, 15624, 10941, 5034, 2499, 2320, 706, 490]}, {'year': 2017, 'bins': [0, 100000, 200000, 300000, 400000, 500000, 750000, 1000000, 2000000], 'priceBins': [10746, 15646, 13604, 7091, 3171, 2967, 965, 635]}, {'year': 2018, 'bins': [0, 100000, 200000, 300000, 400000, 500000, 750000, 1000000, 2000000], 'priceBins': [9273, 15523, 15342, 8326, 3746, 3334, 981, 699]}, {'year': 2019, 'bins': [0, 100000, 200000, 300000, 400000, 500000, 750000, 1000000, 2000000], 'priceBins': [7809, 15737, 16831, 9620, 3953, 3244, 940, 665]}, {'year': 2020, 'bins': [0, 100000, 200000, 300000, 400000, 500000, 750000, 1000000, 2000000], 'priceBins': [6525, 12719, 13822, 8187, 3603, 3058, 827, 554]}, {'year': 2021, 'bins': [0, 100000, 200000, 300000, 400000, 500000, 750000, 1000000, 2000000], 'priceBins': [6534, 14080, 16233, 10786, 4989, 4289, 1357, 962]}, {'year': 2022, 'bins': [0, 100000, 200000, 300000, 400000, 500000, 750000, 1000000, 2000000], 'priceBins': [4678, 12309, 17399, 13026, 6392, 5555, 1727, 1208]}, {'year': 2023, 'bins': [0, 100000, 200000, 300000, 400000, 500000, 750000, 1000000, 2000000], 'priceBins': [3932, 10857, 16764, 14754, 7690, 5946, 1752, 1183]}, {'year': 2024, 'bins': [0, 100000, 200000, 300000, 400000, 500000, 750000, 1000000, 2000000], 'priceBins': [3462, 8603, 14476, 14840, 9020, 7042, 2072, 1464]}, {'year': 2025, 'bins': [0, 100000, 200000, 300000, 400000, 500000, 750000, 1000000, 2000000], 'priceBins': [2229, 5423, 9644, 11762, 7962, 6386, 1835, 1221]}]